cmake_minimum_required(VERSION 3.30)
project(fomod_plus_scanner)

add_library(fomod_plus_scanner SHARED)
include(FetchContent)
set(project_type plugin)
set_property(TARGET fomod_plus_scanner PROPERTY CXX_STANDARD 20)

set(CMAKE_GENERATOR_PLATFORM x64)

FetchContent_Declare(json URL https://github.com/nlohmann/json/releases/download/v3.11.3/json.tar.xz)
FetchContent_Declare(pugixml GIT_REPOSITORY https://github.com/zeux/pugixml GIT_TAG v1.14)
FetchContent_MakeAvailable(pugixml json)

target_include_directories(
        fomod_plus_scanner
        PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}
        ${CMAKE_CURRENT_SOURCE_DIR}/../share
        ${CMAKE_CURRENT_SOURCE_DIR}/../share/FOMODData
        ${RESOURCE_DIR}
        ${MO2_UIBASE_INCLUDE_DIRS}
        ${MO2_ARCHIVE_INCLUDE_DIRS}
)

if (MSVC)
    target_compile_options(
            fomod_plus_scanner
            PRIVATE
            /bigobj # increase number of sections in .obj file
            /W4     # level 4 warnings
            /WX     # treat all compiler warnings as errors
            /wd4201 # nonstandard extension used: nameless struct/union
            /wd4458 # declaration of 'identifier' hides class member
    )
endif ()

target_link_libraries(fomod_plus_scanner PRIVATE mo2::uibase mo2::archive pugixml nlohmann_json::nlohmann_json Qt6::Core Qt6::Gui Qt6::Widgets)
mo2_configure_plugin(fomod_plus_scanner WARNINGS OFF PRIVATE_DEPENDS archive)

if(MSVC)
    # Ensure PDB is generated
    target_compile_options(fomod_plus_scanner PRIVATE $<$<CONFIG:RelWithDebInfo>:/Zi>)
    target_link_options(fomod_plus_scanner PRIVATE $<$<CONFIG:RelWithDebInfo>:/DEBUG>)

    # Install PDB alongside DLL
    install(FILES $<TARGET_PDB_FILE:fomod_plus_scanner>
            DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO}
            CONFIGURATIONS RelWithDebInfo
            OPTIONAL)
endif()

mo2_install_target(fomod_plus_scanner)
